title: Rhino
description: Rhino is an open-source implementation of JavaScript written entirely in Java
baseurl: "/rhino"
#remote_theme: pmarsceill/just-the-docs
remote_theme: pdmosses/just-the-docs@combination # workaround untill https://github.com/pmarsceill/just-the-docs/pull/448 and https://github.com/pmarsceill/just-the-docs/pull/466 get merged and released
aux_links:
  "Rhino on GitHub":
    - "//github.com/mozilla/rhino"

gem:
  - jekyll-mentions
#  - jekyll-redirect-from

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true
  tools:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
    tutorials:
      name: Tutorials
    tools:
      name: Tools

defaults:
  -
    scope:
      path: ""
      type: docs
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: tools
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: tutorials
    values:
      layout: "default"

encoding: utf-8

relative_links:
  enabled: true
  collections: true

callouts:
  highlight:
    color: green
    opacity: 0.5
  important:
    title: Important
    color: orange
  note:
    title: Note
    color: blue